import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

public class App {
	public static void main(String[] args) {
	Date currentDate = new Date();
	SimpleDateFormat dtFormat = new SimpleDateFormat("dd-MM-yyyy");
	String date = dtFormat.format(currentDate);
	date = "26-05-2021";

	try (PrintWriter writer = new PrintWriter(new File("C:/ykkap/public/storage/ykkap/overtime_workflow/test_" + date +".csv"))) {

	  StringBuilder sb = new StringBuilder();
	  //Header
	sb.append("Employee Nik");
	sb.append(',');
	sb.append("Date");
	sb.append(",");
	sb.append("Shift");
	sb.append(",");
	sb.append("Date Overtime In");
	sb.append(",");
	sb.append("Overtime In");
	sb.append(",");
	sb.append("Date Overtime Out");
	sb.append(",");
	sb.append("Overtime Out");
	sb.append(",");
	sb.append("Overtime Type");
	sb.append(",");
	sb.append("Overtime Formula");
	sb.append(",");
	sb.append("Deducted Break Type");
	sb.append(",");
	sb.append("Remarks");
	sb.append('\n');

	  //Data
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	  sb.append("Employee Nik");
	  sb.append(',');
	  sb.append("Date");
	  sb.append(",");
	  sb.append("Shift");
	  sb.append(",");
	  sb.append("Date Overtime In");
	  sb.append(",");
	  sb.append("Overtime In");
	  sb.append(",");
	  sb.append("Date Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Out");
	  sb.append(",");
	  sb.append("Overtime Type");
	  sb.append(",");
	  sb.append("Overtime Formula");
	  sb.append(",");
	  sb.append("Deducted Break Type");
	  sb.append(",");
	  sb.append("Remarks");
	  sb.append('\n');
	// end loop
	
	  writer.write(sb.toString());

	  System.out.println("done!");

	} catch (FileNotFoundException e) {
	  System.out.println(e.getMessage());
	}

  }
}